---
#  _________________________
# < Vlad configuration file >
#  -------------------------
#         \   ^__^
#          \  (oo)\_______
#             (__)\       )\/\
#                 ||----w |
#                 ||     ||
#
# Change settings here to control how Vlad sets up your box.

  webserver_hostname: 'drupal.local'
  webserver_hostname_alias: 'www.{{ webserver_hostname }}'

# Several install parameters follow:
# - To install a component set it to "y".
# - To leave a component out of the install set the value to "n".

  adminer_install: "y"

  apache_install: "y"

  css_install: "y"

  mailcatcher_install: "y"

  memcached_install: "n"

  munin_install: "n"

  mysql_install: "y"

  php_install: "y"

  redis_install: "n"

  sendmail_install: "y"

  solr_install: "n"

  varnish_install: "y"  

  xhprof_install: "y"  

# HTTP port for the web server
  http_port: 8080

# HTTP port for the Varnish cache
  varnish_http_port: 80

# Administration email (used in instances when a server email is needed)
  admin_mail: 'test@example.com'

# PHP Settings

# PHP Version, can be one of "5.3" or "5.4", ansible will error when the wrong version is used.
  php_version: "5.4"

# php.ini settings
  php_memory_limit: 512M
  php_max_execution_time: 60
  php_post_max_size: 100M
  php_upload_max_filesize: 100M
  php_max_execution_time: 90
  php_display_errors: Off
  php_display_startup_errors: Off
  php_html_errors: On
  php_date_timezone: Europe/London

  #php apc
  apc_rfc1867: '1'
  apc_shm_size: '256M'
  apc_shm_segments: '1'
  apc_num_files_hint: '0'

  # mysql
  mysql_port: 3306
  mysql_root_password: sdfds87643y5thgfd
  server_hostname: vlad
  dbname: vladdb
  dbuser: vlad
  dbpass: wibble

  # my.cnf
  mysql_max_allowed_packet: 128M
  innodb_file_per_table: innodb_file_per_table
  mysql_character_set_server: utf8
  mysql_collation_server: utf8_general_ci

  #ssh
  ssh_port: 22

  # varnish
  varnish_memory: 512