---
- name: Ruby | Install RVM
  shell: curl -L https://get.rvm.io | bash -s stable --ruby={{ ruby_version }}
  tags: ruby

- name: Ruby | Add RVM to bash profile
  lineinfile:
    dest=/home/{{ user }}/.bashrc
    state=present
    line='[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"'
  tags: ruby