---
- name: Apache | install apache2 packages
  apt: pkg={{ item }} state=installed
  tags: apache2
  sudo: true
  with_items:
   - apache2
   - apache2-mpm-prefork
   - apache2-utils

- name: Apache | set up directories (with logs directory)
  file: path=/var/www/site/logs state=directory recurse=yes
  tags: apache2
  sudo: true

- name: Apache | disable default site
  command: a2dissite default
  tags: apache2
  sudo: true

- name: Apache | add custom configuration
  template: src=apache/apache_httpdconf.j2 dest=/etc/apache2/httpd.conf
  tags: apache2
  sudo: true

- name: Apache | change port configuration
  template: src=apache/apache_ports.j2 dest=/etc/apache2/ports.conf
  tags: apache2
  sudo: true

- name: Apache | add vhost
  template: src=apache/apache_vhost.j2 dest=/etc/apache2/sites-enabled/{{ apache_hostname }}.conf
  tags: apache2
  sudo: true
  notify:
    - restart apache2

- name: Apache | enable mod rewrite module
  command: a2enmod rewrite
  tags: apache2
  sudo: true
  notify:
    - restart apache2