---
- name: Drush | add drush pear channel
  command: pear channel-discover pear.drush.org creates=/usr/share/php/.channels/pear.drush.org.reg
  sudo: true

- name: Drush | force upgrade of Console_Getopt
  command: pear upgrade --force Console_Getopt
  sudo: true

- name: Drush | force upgrate of pear
  command: pear upgrade --force pear
  sudo: true

- name: Drush | upgrade all pear other packages
  command: pear upgrade-all
  sudo: true

- name: Drush | install drush
  command: pear install drush/drush creates=/usr/bin/drush
  sudo: true

- name: Drush | run drush once to finalise install
  command: drush
  sudo: true

- name: Drush | run drush once as current user to finalise install
  command: drush

- name: Drush | download the site audit module
  command: drush dl site_audit chdir=~/.drush creates=~/.drush/site_audit
  sudo: true

- name: Drush | download the hacked! module
  command: drush dl hacked chdir=~/.drush creates=~/.drush/hacked
  sudo: true

- name: Drush | clear drush cache
  command: drush cc all 

- name: Drush | copy drush/Drupal installation script
  template: src=drupal_install.j2 dest=/var/www/drupal_install.sh
  sudo: true

- name: Drush | set drush/Drupal installation script to executable
  command: chmod +x /var/www/drupal_install.sh
  sudo: true