---
- name: Drush | add drush pear channel
  command: pear channel-discover pear.drush.org creates=/usr/share/php/.channels/pear.drush.org.reg
  sudo: true

- name: Drush | force upgrade of Console_Getopt
  command: pear upgrade --force Console_Getopt
  sudo: true

- name: Drush | force upgrate of pear
  command: pear upgrade --force pear
  sudo: true

- name: Drush | upgrade all pear other packages
  command: pear upgrade-all
  sudo: true

- name: Drush | install drush
  command: pear install drush/drush creates=/usr/bin/drush
  sudo: true

- name: Drush | run drush once to finalise install
  command: drush
  sudo: true

- name: Drush | run drush once as current user to finalise install
  command: drush

- name: Drush | download the site audit module
  command: drush dl site_audit chdir=~/.drush creates=~/.drush/site_audit
  sudo: true

- name: Drush | download the hacked! module
  command: drush dl hacked chdir=~/.drush creates=~/.drush/hacked
  sudo: true

- name: Drush | clear drush cache
  command: drush cc all 

- name: Drush | copy drush/Drupal 7 installation script
  template: src=drupal/drupal7_install.j2 dest=/var/www/drupal7_install.sh
  sudo: true

- name: Drush | set drush/Drupal 7 installation script to executable
  command: chmod +x /var/www/drupal7_install.sh
  sudo: true

- name: Drush | copy drush/Drupal 8 installation script
  template: src=drupal/drupal8_install.j2 dest=/var/www/drupal8_install.sh
  sudo: true

- name: Drush | set drush/Drupal 8 installation script to executable
  command: chmod +x /var/www/drupal8_install.sh
  sudo: true

- name: Drush | get latest version of Drush
  git: repo=https://github.com/drush-ops/drush.git dest=~/drush

- name: Drush | set drush to executable
  command: chmod u+x drush chdir=~/drush

- name: Drush | add drush-master alias to .bashrc file
  lineinfile: dest=~/.bashrc state=present line='alias drush-master=/home/vagrant/drush/drush'

- name: Drush | run composer install in drush
  command: composer install chdir=~/drush creates=~/drush/composer.lock

#chmod u+x /home/vagrant/drush/drush
#alias drush-master=/home/vagrant/drush/drush
#composer install
