---
- name: PHP | install php packages
  apt: pkg={{ item }} state=installed
  sudo: true
  with_items:
   - php-apc
   - php-pear
   - php5
   - php5-cli
   - php5-common
   - php5-dev
   - php5-gd
   - php5-mysql
   - php5-xmlrpc
   - php-soap
   - php5-curl
  notify:
    - restart apache2
   
- name: PHP | change php apache2 memory_limit
  lineinfile: dest=/etc/php5/apache2/php.ini regexp="^memory_limit = " insertafter="^#memory_limit = " line="memory_limit = {{ php_memory_limit }}"
  sudo: true
  notify:
    - restart apache2
  
- name: PHP | change php apache2 max_execution_time
  lineinfile: dest=/etc/php5/apache2/php.ini regexp="^max_execution_time = " insertafter="^#max_execution_time = " line="max_execution_time = {{ php_max_execution_time }}"
  sudo: true
  notify:
    - restart apache2

- name: PHP | change php apache2 post_max_size
  lineinfile: dest=/etc/php5/apache2/php.ini regexp="^post_max_size = " insertafter="^#post_max_size = " line="post_max_size = {{ php_post_max_size }}"
  sudo: true
  notify:
    - restart apache2

- name: PHP | change php apache2 upload_max_filesize
  lineinfile: dest=/etc/php5/apache2/php.ini regexp="^upload_max_filesize = " insertafter="^#upload_max_filesize = " line="upload_max_filesize = {{ php_upload_max_filesize }}"
  sudo: true
  notify:
    - restart apache2

- name: PHP | change php apache2 max_execution_time
  lineinfile: dest=/etc/php5/apache2/php.ini regexp="^max_execution_time = " insertafter="^#max_execution_time = " line="max_execution_time = {{ php_max_execution_time }}"
  sudo: true
  notify:
    - restart apache2

- name: PHP | change php apache2 display_errors
  lineinfile: dest=/etc/php5/apache2/php.ini regexp="^display_errors = " insertafter="^#display_errors = " line="display_errors = {{ php_display_errors }}"
  sudo: true
  notify:
    - restart apache2

- name: PHP | change php apache2 display_startup_errors
  lineinfile: dest=/etc/php5/apache2/php.ini regexp="^display_startup_errors = " insertafter="^#display_startup_errors = " line="display_startup_errors = {{ php_display_startup_errors }}"
  sudo: true
  notify:
    - restart apache2
 
- name: PHP | change php apache2 html_errors
  lineinfile: dest=/etc/php5/apache2/php.ini regexp="^html_errors = " insertafter="^#html_errors = " line="html_errors = {{ php_html_errors }}"
  sudo: true
  notify:
    - restart apache2
 
- name: PHP | change php apache2 date_timezone
  lineinfile: dest=/etc/php5/apache2/php.ini regexp="^date_timezone = " insertafter="^#date_timezone = " line="date_timezone = {{ php_date_timezone }}"
  sudo: true
  notify:
    - restart apache2
    
- name: PHP | Change APC configuration file apc.ini
  template: src=php/php_apache2_apc.ini.j2 dest=/etc/php5/conf.d/apc.ini
  sudo: true
  notify:
    - restart apache2

- name: PHP | Install Composer
  shell: curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer
  sudo: true

