---
# largley compiled from https://drupal.org/node/2148299
# also http://andres.jaimes.net/878/setup-lucene-solr-centos-tomcat/
- name: Solr | install java and tomcat packages
  yum: pkg={{ item }} state=installed
  sudo: true
  with_items:
   - icedtea-web
   - tomcat6
   - tomcat6-webapps
   - tomcat6-admin-webapps
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Solr | install java and tomcat packages
  apt: pkg={{ item }} state=installed
  sudo: true
  with_items:
   - openjdk-7-jre
   - tomcat6
   - tomcat6-extras
   - tomcat6-admin
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Solr | setup the tomcat users file
  copy: src=tomcat/tomcat-users.xml dest=/etc/tomcat6/tomcat-users.xml
  sudo: true
  notify:
   - restart tomcat6

- name: Solr | change port of tomcat server
  copy: src=tomcat/server.xml dest=/etc/tomcat6/server.xml
  sudo: true

- name: Solr | ensure correct run level of tomcat
  service: name=tomcat6 enabled=yes
  sudo: true
  notify:
   - restart tomcat6

- name: Solr | force (re)start of tomcat6
  command: service tomcat6 restart
  sudo: true

- name: Solr | get iptables rules
  shell: /sbin/iptables -L
  register: iptablesrules
  sudo: true

- name: Solr | add apache iptable rule
  command: /sbin/iptables -I INPUT 1 -p tcp --dport 8081 -j ACCEPT -m comment --comment "tomcat"
  sudo: true
  when: iptablesrules.stdout.find("tomcat") == -1
  notify:
   - save iptables

- name: Solr | download apache commons logging
  command: wget http://mirror.gopotato.co.uk/apache/commons/logging/binaries/commons-logging-1.1.3-bin.tar.gz creates=/home/{{ user }}/commons-logging-1.1.3-bin.tar.gz

- name: Solr | extract apache commons logging
  command: tar -zxf commons-logging-1.1.3-bin.tar.gz creates=/home/{{ user }}/commons-logging-1.1.3
  sudo: true

- name: Solr | list commons-logging files (in order to copy)
  command: ls -1 /home/{{ user }}/commons-logging-1.1.3/
  register: commonsfiles

- name: Solr | copy apache commons logging
  command: cp -r /home/{{ user }}/commons-logging-1.1.3/{{ item }} /usr/share/tomcat6/lib creates=/usr/share/tomcat6/lib/{{ item }}
  sudo: true
  with_items: commonsfiles.stdout_lines

- name: Solr | download SLF4J
  command: wget http://www.slf4j.org/dist/slf4j-1.7.5.tar.gz creates=/home/{{ user }}/slf4j-1.7.5.tar.gz

- name: Solr | extract SLF4J
  command: tar -zxf slf4j-1.7.5.tar.gz creates=/home/{{ user }}/slf4j-1.7.5

- name: Solr | list slf4j files (in order to copy)
  command: ls -1 /home/{{ user }}/slf4j-1.7.5/
  register: slf4jfiles

- name: Solr | copy SLF4J
  command: cp -r /home/{{ user }}/slf4j-1.7.5/{{ item }} /usr/share/tomcat6/lib creates=/usr/share/tomcat6/lib/{{ item }}
  sudo: true
  with_items: slf4jfiles.stdout_lines

- name: Solr | download Solr
  command: wget http://www.mirrorservice.org/sites/ftp.apache.org/lucene/solr/4.6.0/solr-4.6.0.tgz creates=/home/{{ user }}/solr-4.6.0.tgz

- name: Solr | extract Solr
  command: tar -zxf /home/{{ user }}/solr-4.6.0.tgz creates=/home/{{ user }}/solr-4.6.0

- name: Solr | copy Solr war file
  command: cp /home/{{ user }}/solr-4.6.0/dist/solr-4.6.0.war /var/lib/tomcat6/webapps/solr.war creates=/var/lib/tomcat6/webapps/solr.war
  sudo: true

- name: Solr | list solr files (in order to copy)
  command: ls -1 /home/{{ user }}/solr-4.6.0/example/solr/
  register: solrfiles 

- name: Solr | copy Solr instance
  command: cp -ar /home/{{ user }}/solr-4.6.0/example/solr/{{ item }} /home/solr creates=/home/solr/{{ item }}
  sudo: true
  with_items: solrfiles.stdout_lines
    
- name: Solr | rename the collection1 directory to vlad
  command: mv /home/solr/collection1 /home/solr/vlad creates=/home/solr/vlad
  sudo: true

- name: Solr | Remove the collection1 collection if it is still there
  file: path=/home/solr/collection1 state=absent
  sudo: true 

- name: Solr | change the name of the collection
  lineinfile: dest=/home/solr/vlad/core.properties regexp="^name=" insertafter="^name=" line="name=vlad"
  sudo: true

- name: Solr | create a solr lib directory
  file: path=/home/solr/lib state=directory
  sudo: true

- name: Solr | list all jar files that are part of solr (in order to copy)
  shell: ls -1 /home/{{ user }}/solr-4.6.0/dist/ | grep .jar
  register: solrjarfiles

##- name: Solr | make the lib/dist directory for the jar files to live in
##  command: mkdir -p /home/solr/lib/dist/ creates=/home/solr/lib/dist/
##  sudo: true

- name: Solr | copy solr lib files
  command: cp /home/{{ user }}/solr-4.6.0/dist/{{ item }} /home/solr/lib/{{ item }} creates=/home/solr/lib/{{ item }}
  with_items: solrjarfiles.stdout_lines
  sudo: true

- name: Solr | copy the web.xml tomcat solr integration file
  copy: src=tomcat/web.xml dest=/var/lib/tomcat6/webapps/solr/WEB-INF/web.xml
  sudo: true

- name: Solr | copy the properties file
  copy: src=tomcat/log4j.properties dest=/usr/share/tomcat6/lib/log4j.properties
  sudo: true

- name: Solr | make the vlad data directory
  command: mkdir /home/solr/vlad/data creates=/home/solr/vlad/data
  sudo: true

- name: Solr | get Drupal solr integration
  git: repo=http://git.drupal.org/project/search_api_solr.git version=7.x-1.3 dest=/home/{{ user }}/search_api_solr

- name: Solr | copy Drupal Solr config into Solr
  shell: cp -r /home/{{ user }}/search_api_solr/solr-conf/4.x/. /home/solr/vlad/conf/
  sudo: true
  notify:
   - restart tomcat6
#
#- name: Solr | make the lib/contrib directory for the extension to live in
#  command: mkdir -p /home/solr/lib/contrib/ creates=/home/solr/lib/contrib/
#  sudo: true
#
#- name: Solr | copy the needed class directories over
#  command: cp -r /home/{{ user }}/solr-4.6.0/contrib/{{ item }} /home/solr/lib/contrib/{{ item }} creates=/home/solr/lib/contrib/{{ item }}
#  with_items:
#    - analysis-extras
#    - clustering
#    - dataimporthandler
#    - extraction
#    - langid
#    - uima
#    - velocity
#  sudo: true
#
#- name: Solr | ensure tomcat/Solr directory has correct owner
#  command: chown tomcat:tomcat -R /home/solr
#  sudo: true

#- name: Solr | copy the solr config file
#  copy: src=solr/solrconfig.xml dest=/home/solr/vlad/conf/solrconfig.xml owner=tomcat group=tomcat mode=0644
#  sudo: true
##  notify:
##   - restart tomcat6
#
##- name: Solr | copy the solr schema file
##  copy: src=solr/synonyms.txt dest=/home/solr/vlad/conf/synonyms.txt owner=tomcat group=tomcat mode=0644
##  sudo: true
##  notify:
##   - restart tomcat6
#
##- name: Solr | copy the solr schema file
##  copy: src=schema.xml dest=/home/solr/vlad/conf/schema.xml owner=tomcat group=tomcat mode=0644
##  sudo: true
##  notify:
##   - restart tomcat6
