---
- hosts: all
  gather_facts: false
  vars_files:
    - "./vars/defaults/vagrant.yml"
    - "./vars/defaults/general.yml"
    - [ "../../../settings/vlad-settings.yml", "../settings.yml", "../example.settings.yml" ]

  tasks:

  - name: local actions | check local ip address is defined
    fail: msg="The system may not be provisioned according to the CMDB status."
    when: local_ip_address is not defined

  - name: local actions | write local host.ini file
    template: src=templates/host.j2 dest=../host.ini
    delegate_to: 127.0.0.1

  - name: local actions | remove reference of host from local hosts file
    lineinfile:
        dest='{{ hosts_file_location }}'
        state=absent
        regexp='.*?\s{{ webserver_hostname }} {{ webserver_hostname_alias }} adminer.{{ webserver_hostname }} xhprof.{{ webserver_hostname }} logs.{{ webserver_hostname }}'
    delegate_to: 127.0.0.1
    sudo: true

  - name: local actions | add reference of host to local hosts file
    lineinfile:
        dest='{{ hosts_file_location }}'
        state=present
        line='{{ local_ip_address }} {{ webserver_hostname }} {{ webserver_hostname_alias }} adminer.{{ webserver_hostname }} xhprof.{{ webserver_hostname }} logs.{{ webserver_hostname }}'
    delegate_to: 127.0.0.1
    sudo: true

  # ssh-add

  # @TODO: If use_host_id is set to anyhthing other than "n", test for the presence of ~/.ssh/config on the host box. If it's missing, fail or at least feedback.

  - name: local actions | add default identities from host to guest
    local_action: command ssh-add
    when: use_host_id == "y"

  - name: local actions | add custom identity from host to guest
    local_action: command ssh-add {{ use_host_ssh_key }}
    when: use_host_id != "y" and use_host_id != "n"
