---
- name: Drush | add drush pear channels
  action: command pear channel-discover pear.drush.org creates=/usr/share/php/.channels/pear.drush.org.reg
  sudo: true

- name: Drush | force upgrade of Console_Getopt
  command: pear upgrade --force Console_Getopt
  sudo: true
  
- name: Drush | force upgrate of pear
  command: pear upgrade --force pear
  sudo: true

- name: Drush | upgrade all pear other packages
  command: pear upgrade-all
  sudo: true

- name: Drush | install drush
  command: pear install drush/drush creates=/usr/bin/drush
  sudo: true

- name: Drush | run drush once to finalise install
  command: drush

- name: Drush | get site audit drush extension tar file
  command: wget http://ftp.drupal.org/files/projects/site_audit-7.x-1.5.tar.gz chdir=~/.drush
  
- name: Drush | extract site audit drush extension tar file
  command: tar -zxf site_audit-7.x-1.5.tar.gz chdir=~/.drush

- name: Drush | remove original site audit drush extension tar file
  command: rm site_audit-7.x-1.5.tar.gz chdir=~/.drush
  
- name: Drush | clear drush cache
  command: drush cc all 