---
- name: Munin | install munin
  apt: pkg={{ item }} state=installed
  sudo: true
  with_items:
   - munin-common
   - munin-node

- name: Munin | add munin node config
  template: src=munin_node.j2 dest=/etc/munin/munin-node.conf
  sudo: true

- name: Munin | get iptables rules
  shell: iptables -L
  register: iptablesrules
  sudo: true

- name: Munin | add munin iptables
  command: iptables -A INPUT -p tcp --dport 4949 -s {{ external_ip_address }} -j ACCEPT
  sudo: true
  when: iptablesrules.stdout.find("munin") == -1
  notify:
   - save iptables

- name: Munin | add munin to startup
  command: update-rc.d munin-node defaults
  sudo: true
  notify:
   - restart munin-node
