---
- hosts: all
  vars:
    #apache
    apache_hostname: 'www.drupal.local'
    apache_hostname_alias: 'drupal.local'
    apache_admin_mail: 'test@example.com'
  tasks:
  - name: local actions | print hostname
    local_action: debug var=apache_hostname

  - name: local actions | remove reference of host from local hosts file
    lineinfile:
        dest=/etc/hosts
        state=absent
        regexp='.*?\s{{ apache_hostname }} www.{{ apache_hostname }} adminer.{{ apache_hostname }} xhprof.{{ apache_hostname }}'
    delegate_to: 127.0.0.1
    sudo: true

  - name: local actions | add reference of host from local hosts file
    lineinfile:
        dest=/etc/hosts
        state=present
        line='{{ ansible_eth1.ipv4.address }} {{ apache_hostname }} www.{{ apache_hostname }} adminer.{{ apache_hostname }} xhprof.{{ apache_hostname }}'
    delegate_to: 127.0.0.1
    sudo: true