---
- hosts: all
  vars:
    #apache
    apache_hostname: 'www.drupal.local'
    apache_hostname_alias: 'drupal.local'
    apache_admin_mail: 'test@example.com'
  tasks:
#- name: local actions | get local IPv4 address
#  local_action: setup filter=ansible_default_ipv4
#  register: local_ipv4_address

#- name: local actions | remote IPv4 address debug
#  local_action: debug var='ansible_eth1.ipv4.address'

#- name: local actions | local IPv4 address debug
#  local_action: debug var='local_ipv4_address.ansible_facts.ansible_default_ipv4.address'

  - name: local actions | print hostname
    local_action: debug var=apache_hostname

  - name: local actions | remove reference of host from local hosts file
    #local_action: lineinfile dest=/etc/hosts state=absent regexp='.*?\s{{ apache_hostname }}'
    lineinfile: dest=/etc/hosts state=absent regexp='.*?\s{{ apache_hostname }}'
    delegate_to: 127.0.0.1
    sudo: true

  - name: local actions | add reference of host from local hosts file
    #local_action: lineinfile dest=/etc/hosts state=present line='{{ ansible_eth1.ipv4.address }} {{ apache_hostname }}'
    lineinfile: dest=/etc/hosts state=present line='{{ ansible_eth1.ipv4.address }} {{ apache_hostname }}'
    delegate_to: 127.0.0.1
    sudo: true