---
- hosts: all
  roles:
    - base
    - mysql
    - apache
    - varnish
    - memcached
    - sendmail
    - solr
  vars:
    #apache
    apache_hostname: 'www.drupal.local'
    apache_hostname_alias: 'drupal.local'
    apache_admin_mail: 'test@example.com'
