---
- hosts: all
  roles:
    - base
    - mysql
    - apache
    - varnish
    - memcached
    - mailcatcher
    - sendmail
    - solr
    - munin
  vars:
    #apache
    apache_hostname: 'drupal.local'
    apache_hostname_alias: 'www.{{ apache_hostname }}'
    apache_admin_mail: 'test@example.com'
