---
- hosts: all
  roles:
    - role: base
    - role: mysql
    - role: php
    - role: apache
    - role: varnish
    - role: memcached
    - role: mailcatcher
    - role: sendmail
    - role: solr
    - role: munin
    - role: css
