---
- name: setup php 'flavour' variable
  when: php_version == "5.4"
  set_fact:
    php_flavour: "php_54"

- name: setup php 'flavour' variable
  when: php_version == "5.3" and ansible_lsb.major_release|int == 12
  set_fact:
    php_flavour: "php_53"

- name: setup php 'flavour' variable
  when: php_version == "5.5" and ansible_lsb.major_release|int == 14
  set_fact:
    php_flavour: "php_54"

- include: debian_php_common.yml
- include: debian_{{ php_flavour }}.yml

- name: check, what PECL uploadprogress is installed
  command: pecl list | grep uploadprogress | wc -l
  register: pecl_uploadprogress_installed
  changed_when: false

- name: install PECL uploadprogress
  command: pecl install uploadprogress creates=/usr/lib/php5/20100525/uploadprogress.so
  tags: php
  sudo: true
  when: php_pecl_uploadprogress and pecl_uploadprogress_installed.stdout == '0'

- name: add PECL uploadprogress apache php.ini setting
  lineinfile: dest=/etc/php5/apache2/php.ini state=present line="extension=uploadprogress.so"
  tags: php
  sudo: true
  when: php_pecl_uploadprogress
  notify:
    - restart apache2
