---
- name: pear | force upgrade of pear
  command: pear upgrade --force pear
  tags: pear
  sudo: true

- name: pear | upgrade all other pear packages
  command: pear upgrade
  register: pear_upgrade_all
  failed_when: "pear_upgrade_all.rc != 0"
  changed_when: "'Nothing to upgrade-all' not in pear_upgrade_all.stdout"
  tags: pear
  sudo: true

- name: pear | clear pear cache
  command: pear clear-cache
  changed_when: False
  tags: pear
  sudo: true